backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/blog"
public_folder: "/assets/blog"
collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/portfolio"
    create: true
    fields:
      - { label: "Client Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["portfolio"] }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
  - name: "portfolio2"
    label: "Portfolio2"
    folder: "src/portfolio2"
    create: true
    fields:
      - { label: "Client Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["portfolio2"] }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
  - name: "stars"
    label: "Stars"
    folder: "src/stars"
    create: true
    fields:
      - { label: "blockquote", name: "blockquote", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["stars"] }
      - { label: "Text", name: "text", widget: "string" }
  - name: "team"
    label: "Team"
    folder: "src/team"
    create: true
    fields:
      - { label: "Member Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["team"] }
      - { label: "Text", name: "name", widget: "string" }
      - { label: "facebook", name: "facebook", widget: "string" }
  - name: "pricelist"
    label: "Pricelist"
    folder: "src/pricelist"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", default: ["pricelist"] }
      - { label: "Price", name: "price", widget: "string" }
  - name: "products"
    label: "Products"
    folder: "src/products"
    create: true
    fields:
      - { label: "Member Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: ["products"] }
      - { label: "Imagealt", name: "imageAlt", widget: "string" }
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
